---
Name: module-manager
Before:
    - '#site'
---
Jaedb\ModuleManager\ModuleManager:
  positions:
    - 'before-content'
    - 'after-content'
    - 'footer'
    - 'sidebar'
SilverStripe\Control\Controller:
  extensions:
    - Jaedb\ModuleManager\ModulePageController